# Generated by Django 3.2 on 2022-04-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_fund',
            field=models.IntegerField(default=0, verbose_name='총 펀딩 금액'),
        ),
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(verbose_name='펀딩 종료일'),
        ),
    ]
